AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  ApiUIV1WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: ApiUIV1WebSocketApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
  ApiUIV1WebRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiUIV1WebSocketApi
      RouteKey: $default
      AuthorizationType: NONE
      OperationName: WebRouteRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ApiUIV1WebRouteIntegration            
  ApiUIV1WebConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiUIV1WebSocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ApiUIV1WebConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ApiUIV1WebRouteIntegration  
  ApiUIV1WebDisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiUIV1WebSocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: ApiUIV1WebDisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ApiUIV1WebRouteIntegration             
  ApiUIV1WebRouteIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiUIV1WebSocketApi
      Description: ApiUIV1WebRouteIntegration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiUIV1WebSocketApiHandler.Arn}/invocations
  ApiUIV1WebSocketApiHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: 'dist/handlers/api-ui-ws-listener.handler'
      Timeout: 30
      MemorySize: 512
      Runtime: nodejs10.x
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AmazonDynamoDBFullAccess
        
  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
    - ApiUIV1WebConnectRoute
    - ApiUIV1WebDisconnectRoute
    - ApiUIV1WebRoute
    Properties:
      ApiId: !Ref ApiUIV1WebSocketApi
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Prod
      Description: Prod Stage
      DeploymentId: !Ref Deployment
      ApiId: !Ref ApiUIV1WebSocketApi
  ApiUIV1WebSocketApiPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - ApiUIV1WebSocketApi
      - ApiUIV1WebSocketApiHandler
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ApiUIV1WebSocketApiHandler
      Principal: apigateway.amazonaws.com      
Outputs:      
  WebSocketURI:
    Description: "The WSS Protocol URI to connect to"
    Value: !Join [ '', [ 'wss://', !Ref ApiUIV1WebSocketApi, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/',!Ref 'Stage'] ]      